---
title: "UFO Sightings in `r params$state`"
author: "April Johns"
date: "2025-11-10"
output: html_document
params: 
  state: "co" 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)

ufo_raw <- read_csv('../data/ufo_sightings.csv')

ufo_state <- ufo_raw %>% 
  mutate(date_time = mdy_hm(date_time),
         sighting_year = year(date_time)) %>% 
  filter(state == params$state)

```

```{r}
# plot 

ufo_state %>% 
  group_by(state) %>% 
  summarise(n_state = n()) %>% 
  ungroup() %>% 
  ggplot() + 
  geom_col(aes(x = state, y = n_state))

```

The graph above displays the *ufo sightings* reported in `r params$state`.


```{r}

library(leaflet)

pal <- colorQuantile("YlOrRd", NULL, n = 8)
leaflet(ufo_raw) %>% 
  addTiles() %>%
  addCircleMarkers(color = ~pal(encounter_length))

```

```{r} 
library(plotly)

ufo_shape <- ufo_raw %>% 
  filter(ufo_shape %in% c('chevron', 'disk', 'fireball')) 

ufo_shape_plot <- ufo_shape %>% 
  ggplot(aes(x = ufo_shape)) +
  geom_bar(position = "dodge")

ggplotly(ufo_shape_plot)

```

```{r}
library(DT)

ufo_us <- ufo_raw %>% 
  filter(country == 'us')

datatable(ufo_us, options = list(pageLength = 5))
```





